// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alliance.proto

/*
Package chremoas_esi is a generated protocol buffer package.

It is generated from these files:
	alliance.proto
	character.proto
	common.proto
	corporation.proto
	search.proto

It has these top-level messages:
	GetAlliancesRequest
	GetAlliancesResponse
	GetAllianceByIdRequest
	GetAllianceByIdResponse
	GetAllianceCorporationsByIdRequest
	GetAllianceCorporationsByIdResponse
	GetAllianceIconsByIdRequest
	GetAllianceIconsByIdResponse
	GetAllianceNamesByIdsRequest
	GetAllianceNamesByIdsResponse
	GetCharacterByIdRequest
	GetCharacterByIdResponse
	Alliance
	Icons
	AllianceNames
	Character
	Corporation
	GetCorporationByIdRequest
	GetCorporationByIdResponse
	SearchRequest
	SearchResponse
*/
package chremoas_esi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetAlliancesRequest struct {
}

func (m *GetAlliancesRequest) Reset()                    { *m = GetAlliancesRequest{} }
func (m *GetAlliancesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAlliancesRequest) ProtoMessage()               {}
func (*GetAlliancesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetAlliancesResponse struct {
	Ids []int32 `protobuf:"varint,1,rep,packed,name=Ids" json:"Ids,omitempty"`
}

func (m *GetAlliancesResponse) Reset()                    { *m = GetAlliancesResponse{} }
func (m *GetAlliancesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAlliancesResponse) ProtoMessage()               {}
func (*GetAlliancesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetAlliancesResponse) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetAllianceByIdRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *GetAllianceByIdRequest) Reset()                    { *m = GetAllianceByIdRequest{} }
func (m *GetAllianceByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllianceByIdRequest) ProtoMessage()               {}
func (*GetAllianceByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetAllianceByIdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAllianceByIdResponse struct {
	Alliance *Alliance `protobuf:"bytes,1,opt,name=Alliance" json:"Alliance,omitempty"`
}

func (m *GetAllianceByIdResponse) Reset()                    { *m = GetAllianceByIdResponse{} }
func (m *GetAllianceByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllianceByIdResponse) ProtoMessage()               {}
func (*GetAllianceByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetAllianceByIdResponse) GetAlliance() *Alliance {
	if m != nil {
		return m.Alliance
	}
	return nil
}

// GetAllianceCorporationsById
type GetAllianceCorporationsByIdRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *GetAllianceCorporationsByIdRequest) Reset()         { *m = GetAllianceCorporationsByIdRequest{} }
func (m *GetAllianceCorporationsByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllianceCorporationsByIdRequest) ProtoMessage()    {}
func (*GetAllianceCorporationsByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4}
}

func (m *GetAllianceCorporationsByIdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAllianceCorporationsByIdResponse struct {
	Ids []int32 `protobuf:"varint,1,rep,packed,name=Ids" json:"Ids,omitempty"`
}

func (m *GetAllianceCorporationsByIdResponse) Reset()         { *m = GetAllianceCorporationsByIdResponse{} }
func (m *GetAllianceCorporationsByIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllianceCorporationsByIdResponse) ProtoMessage()    {}
func (*GetAllianceCorporationsByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5}
}

func (m *GetAllianceCorporationsByIdResponse) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetAllianceIconsByIdRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
}

func (m *GetAllianceIconsByIdRequest) Reset()                    { *m = GetAllianceIconsByIdRequest{} }
func (m *GetAllianceIconsByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllianceIconsByIdRequest) ProtoMessage()               {}
func (*GetAllianceIconsByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetAllianceIconsByIdRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAllianceIconsByIdResponse struct {
	Icons *Icons `protobuf:"bytes,1,opt,name=Icons" json:"Icons,omitempty"`
}

func (m *GetAllianceIconsByIdResponse) Reset()                    { *m = GetAllianceIconsByIdResponse{} }
func (m *GetAllianceIconsByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllianceIconsByIdResponse) ProtoMessage()               {}
func (*GetAllianceIconsByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetAllianceIconsByIdResponse) GetIcons() *Icons {
	if m != nil {
		return m.Icons
	}
	return nil
}

type GetAllianceNamesByIdsRequest struct {
	Ids []int32 `protobuf:"varint,1,rep,packed,name=Ids" json:"Ids,omitempty"`
}

func (m *GetAllianceNamesByIdsRequest) Reset()                    { *m = GetAllianceNamesByIdsRequest{} }
func (m *GetAllianceNamesByIdsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAllianceNamesByIdsRequest) ProtoMessage()               {}
func (*GetAllianceNamesByIdsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetAllianceNamesByIdsRequest) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetAllianceNamesByIdsResponse struct {
	Names []*AllianceNames `protobuf:"bytes,1,rep,name=Names" json:"Names,omitempty"`
}

func (m *GetAllianceNamesByIdsResponse) Reset()                    { *m = GetAllianceNamesByIdsResponse{} }
func (m *GetAllianceNamesByIdsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAllianceNamesByIdsResponse) ProtoMessage()               {}
func (*GetAllianceNamesByIdsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetAllianceNamesByIdsResponse) GetNames() []*AllianceNames {
	if m != nil {
		return m.Names
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAlliancesRequest)(nil), "chremoas.esi.GetAlliancesRequest")
	proto.RegisterType((*GetAlliancesResponse)(nil), "chremoas.esi.GetAlliancesResponse")
	proto.RegisterType((*GetAllianceByIdRequest)(nil), "chremoas.esi.GetAllianceByIdRequest")
	proto.RegisterType((*GetAllianceByIdResponse)(nil), "chremoas.esi.GetAllianceByIdResponse")
	proto.RegisterType((*GetAllianceCorporationsByIdRequest)(nil), "chremoas.esi.GetAllianceCorporationsByIdRequest")
	proto.RegisterType((*GetAllianceCorporationsByIdResponse)(nil), "chremoas.esi.GetAllianceCorporationsByIdResponse")
	proto.RegisterType((*GetAllianceIconsByIdRequest)(nil), "chremoas.esi.GetAllianceIconsByIdRequest")
	proto.RegisterType((*GetAllianceIconsByIdResponse)(nil), "chremoas.esi.GetAllianceIconsByIdResponse")
	proto.RegisterType((*GetAllianceNamesByIdsRequest)(nil), "chremoas.esi.GetAllianceNamesByIdsRequest")
	proto.RegisterType((*GetAllianceNamesByIdsResponse)(nil), "chremoas.esi.GetAllianceNamesByIdsResponse")
}

func init() { proto.RegisterFile("alliance.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x4f, 0xb3, 0x40,
	0x10, 0x7e, 0x69, 0x5f, 0x8c, 0x99, 0x36, 0xad, 0xd9, 0xda, 0xda, 0x50, 0x4d, 0xea, 0xaa, 0x09,
	0xd5, 0x48, 0x5a, 0x34, 0xf1, 0xac, 0x1e, 0x0c, 0x07, 0x3d, 0xac, 0x07, 0xaf, 0x22, 0x6c, 0x22,
	0x49, 0x61, 0x2b, 0x8b, 0x26, 0xde, 0xfd, 0x51, 0xfe, 0x3c, 0xe3, 0xf2, 0x11, 0xb6, 0x65, 0x69,
	0xbd, 0x91, 0x99, 0xe7, 0x63, 0x86, 0x79, 0x00, 0x3a, 0xee, 0x7c, 0x1e, 0xb8, 0x91, 0x47, 0xad,
	0x45, 0xcc, 0x12, 0x86, 0xda, 0xde, 0x6b, 0x4c, 0x43, 0xe6, 0x72, 0x8b, 0xf2, 0xc0, 0x68, 0x7b,
	0x2c, 0x0c, 0x59, 0x94, 0xf6, 0x70, 0x1f, 0x7a, 0x77, 0x34, 0xb9, 0xce, 0x08, 0x9c, 0xd0, 0xb7,
	0x77, 0xca, 0x13, 0x6c, 0xc2, 0xae, 0x5c, 0xe6, 0x0b, 0x16, 0x71, 0x8a, 0x76, 0xa0, 0xe9, 0xf8,
	0x7c, 0xa8, 0x8d, 0x9b, 0xa6, 0x4e, 0x7e, 0x1f, 0xb1, 0x09, 0x83, 0x12, 0xf2, 0xe6, 0xd3, 0xf1,
	0x33, 0x0d, 0xd4, 0x81, 0x86, 0xe3, 0x0f, 0xb5, 0xb1, 0x66, 0xea, 0xa4, 0xe1, 0xf8, 0xf8, 0x1e,
	0xf6, 0x56, 0x90, 0x99, 0xac, 0x0d, 0xdb, 0x79, 0x5d, 0x10, 0x5a, 0xf6, 0xc0, 0x2a, 0x0f, 0x6d,
	0xe5, 0x5d, 0x52, 0xe0, 0xf0, 0x25, 0xe0, 0x92, 0xdc, 0x2d, 0x8b, 0x17, 0x2c, 0x76, 0x93, 0x80,
	0x45, 0xbc, 0x6e, 0x88, 0x2b, 0x38, 0xaa, 0x65, 0x29, 0xf7, 0x3c, 0x87, 0x51, 0x89, 0xe8, 0x78,
	0x6b, 0x7c, 0x1c, 0xd8, 0xaf, 0x86, 0x67, 0x06, 0x13, 0xd0, 0x45, 0x31, 0x5b, 0xb7, 0x27, 0xaf,
	0x2b, 0x5a, 0x24, 0x45, 0xe0, 0xa9, 0x24, 0xf5, 0xe0, 0x86, 0x54, 0x48, 0xe5, 0xb7, 0xaa, 0x98,
	0x95, 0xc0, 0x81, 0x82, 0x91, 0xb9, 0xcf, 0x40, 0x17, 0x55, 0x41, 0x6a, 0xd9, 0xa3, 0xea, 0x97,
	0x2d, 0x20, 0x24, 0x45, 0xda, 0xdf, 0xff, 0xa1, 0x9b, 0x37, 0x1e, 0x69, 0xfc, 0x11, 0x78, 0x14,
	0x3d, 0x41, 0xbb, 0x9c, 0x12, 0x74, 0x28, 0xeb, 0x54, 0x04, 0xcb, 0xc0, 0x75, 0x90, 0x74, 0x3a,
	0xfc, 0x0f, 0x3d, 0x43, 0x77, 0x29, 0x2a, 0xe8, 0x58, 0x49, 0x2c, 0x9d, 0xc1, 0x38, 0x59, 0x83,
	0x2a, 0x1c, 0xbe, 0x34, 0xe9, 0x9e, 0xcb, 0x41, 0x40, 0x53, 0xa5, 0x90, 0x22, 0x69, 0xc6, 0xec,
	0x0f, 0x8c, 0x62, 0x0c, 0x26, 0x7d, 0x67, 0x45, 0x4c, 0xd0, 0x44, 0x29, 0xb6, 0x9c, 0x3c, 0xe3,
	0x74, 0x13, 0x68, 0x61, 0x18, 0x43, 0xbf, 0x32, 0x1a, 0x48, 0x2d, 0xb3, 0x92, 0x38, 0xe3, 0x6c,
	0x23, 0x6c, 0xee, 0xf9, 0xb2, 0x25, 0x7e, 0x35, 0x17, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa9,
	0xde, 0xe6, 0xba, 0x98, 0x04, 0x00, 0x00,
}
