// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alliance.proto

/*
Package chremoas_esi is a generated protocol buffer package.

It is generated from these files:
	alliance.proto

It has these top-level messages:
	AllianceResponse
	Alliance
*/
package chremoas_esi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import chremoas_esi1 "."

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AllianceResponse struct {
	Result *Alliance `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
}

func (m *AllianceResponse) Reset()                    { *m = AllianceResponse{} }
func (m *AllianceResponse) String() string            { return proto.CompactTextString(m) }
func (*AllianceResponse) ProtoMessage()               {}
func (*AllianceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AllianceResponse) GetResult() *Alliance {
	if m != nil {
		return m.Result
	}
	return nil
}

type Alliance struct {
	Id           int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Ticker       string `protobuf:"bytes,3,opt,name=Ticker" json:"Ticker,omitempty"`
	ExecutorCorp int32  `protobuf:"varint,4,opt,name=ExecutorCorp" json:"ExecutorCorp,omitempty"`
	DateFounded  int64  `protobuf:"varint,5,opt,name=DateFounded" json:"DateFounded,omitempty"`
}

func (m *Alliance) Reset()                    { *m = Alliance{} }
func (m *Alliance) String() string            { return proto.CompactTextString(m) }
func (*Alliance) ProtoMessage()               {}
func (*Alliance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Alliance) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Alliance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Alliance) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *Alliance) GetExecutorCorp() int32 {
	if m != nil {
		return m.ExecutorCorp
	}
	return 0
}

func (m *Alliance) GetDateFounded() int64 {
	if m != nil {
		return m.DateFounded
	}
	return 0
}

func init() {
	proto.RegisterType((*AllianceResponse)(nil), "chremoas.esi.AllianceResponse")
	proto.RegisterType((*Alliance)(nil), "chremoas.esi.Alliance")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AllianceQuery service

type AllianceQueryClient interface {
	GetAlliance(ctx context.Context, in *chremoas_esi1.EntityQueryRequest, opts ...client.CallOption) (*AllianceResponse, error)
}

type allianceQueryClient struct {
	c           client.Client
	serviceName string
}

func NewAllianceQueryClient(serviceName string, c client.Client) AllianceQueryClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "chremoas.esi"
	}
	return &allianceQueryClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *allianceQueryClient) GetAlliance(ctx context.Context, in *chremoas_esi1.EntityQueryRequest, opts ...client.CallOption) (*AllianceResponse, error) {
	req := c.c.NewRequest(c.serviceName, "AllianceQuery.GetAlliance", in)
	out := new(AllianceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AllianceQuery service

type AllianceQueryHandler interface {
	GetAlliance(context.Context, *chremoas_esi1.EntityQueryRequest, *AllianceResponse) error
}

func RegisterAllianceQueryHandler(s server.Server, hdlr AllianceQueryHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&AllianceQuery{hdlr}, opts...))
}

type AllianceQuery struct {
	AllianceQueryHandler
}

func (h *AllianceQuery) GetAlliance(ctx context.Context, in *chremoas_esi1.EntityQueryRequest, out *AllianceResponse) error {
	return h.AllianceQueryHandler.GetAlliance(ctx, in, out)
}

func init() { proto.RegisterFile("alliance.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbb, 0x6a, 0xc3, 0x30,
	0x14, 0x86, 0x2b, 0x27, 0x31, 0xed, 0xb1, 0x1b, 0x8a, 0x86, 0x20, 0x32, 0x14, 0xe1, 0xc9, 0x93,
	0x86, 0xf4, 0x09, 0x7a, 0x49, 0x4b, 0x96, 0x42, 0x44, 0x5f, 0x40, 0x91, 0x0f, 0xd4, 0xd4, 0x96,
	0x5c, 0x5d, 0xa0, 0x79, 0x87, 0x3e, 0x74, 0x41, 0x75, 0x42, 0x32, 0x64, 0x93, 0x3e, 0x7d, 0x3a,
	0x9c, 0xff, 0x87, 0xb9, 0xea, 0xba, 0x56, 0x19, 0x8d, 0x62, 0x70, 0x36, 0x58, 0x5a, 0xea, 0x4f,
	0x87, 0xbd, 0x55, 0x5e, 0xa0, 0x6f, 0x97, 0xa5, 0xb6, 0x7d, 0x6f, 0xcd, 0xff, 0x5b, 0xf5, 0x04,
	0x77, 0x8f, 0xa3, 0x2d, 0xd1, 0x0f, 0xd6, 0x78, 0xa4, 0x02, 0x72, 0x89, 0x3e, 0x76, 0x81, 0x11,
	0x4e, 0xea, 0x62, 0xb5, 0x10, 0xa7, 0x03, 0xc4, 0xd1, 0x1f, 0xad, 0xea, 0x97, 0xc0, 0xf5, 0x01,
	0xd2, 0x39, 0x64, 0x9b, 0x26, 0x7d, 0x9c, 0xc9, 0x6c, 0xd3, 0x50, 0x0a, 0xd3, 0x77, 0xd5, 0x23,
	0xcb, 0x38, 0xa9, 0x6f, 0x64, 0x3a, 0xd3, 0x05, 0xe4, 0x1f, 0xad, 0xfe, 0x42, 0xc7, 0x26, 0x89,
	0x8e, 0x37, 0x5a, 0x41, 0xb9, 0xfe, 0x41, 0x1d, 0x83, 0x75, 0xcf, 0xd6, 0x0d, 0x6c, 0x9a, 0xa6,
	0x9c, 0x31, 0xca, 0xa1, 0x78, 0x51, 0x01, 0x5f, 0x6d, 0x34, 0x0d, 0x36, 0x6c, 0xc6, 0x49, 0x3d,
	0x91, 0xa7, 0x68, 0xb5, 0x83, 0xdb, 0xc3, 0x36, 0xdb, 0x88, 0x6e, 0x4f, 0xb7, 0x50, 0xbc, 0x61,
	0x38, 0x6e, 0xc8, 0xcf, 0xe3, 0xac, 0x4d, 0x68, 0xc3, 0x3e, 0x99, 0x12, 0xbf, 0x23, 0xfa, 0xb0,
	0xbc, 0xbf, 0x10, 0x78, 0x2c, 0xa8, 0xba, 0xda, 0xe5, 0xa9, 0xbd, 0x87, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x88, 0x57, 0x5b, 0x46, 0x6b, 0x01, 0x00, 0x00,
}
