// Code generated by protoc-gen-go. DO NOT EDIT.
// source: character.proto

/*
Package chremoas_esi is a generated protocol buffer package.

It is generated from these files:
	character.proto

It has these top-level messages:
	EntityQueryRequest
	CharacterResponse
	Character
*/
package chremoas_esi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntityQueryRequest struct {
	EntityId int32 `protobuf:"varint,1,opt,name=EntityId" json:"EntityId,omitempty"`
}

func (m *EntityQueryRequest) Reset()                    { *m = EntityQueryRequest{} }
func (m *EntityQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*EntityQueryRequest) ProtoMessage()               {}
func (*EntityQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EntityQueryRequest) GetEntityId() int32 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

type CharacterResponse struct {
	Result *Character `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
}

func (m *CharacterResponse) Reset()                    { *m = CharacterResponse{} }
func (m *CharacterResponse) String() string            { return proto.CompactTextString(m) }
func (*CharacterResponse) ProtoMessage()               {}
func (*CharacterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CharacterResponse) GetResult() *Character {
	if m != nil {
		return m.Result
	}
	return nil
}

type Character struct {
	Id             int32   `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name           string  `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Description    string  `protobuf:"bytes,3,opt,name=Description" json:"Description,omitempty"`
	CorporationId  int32   `protobuf:"varint,4,opt,name=CorporationId" json:"CorporationId,omitempty"`
	AllianceId     int32   `protobuf:"varint,5,opt,name=AllianceId" json:"AllianceId,omitempty"`
	Birthday       int64   `protobuf:"varint,6,opt,name=Birthday" json:"Birthday,omitempty"`
	Gender         string  `protobuf:"bytes,7,opt,name=Gender" json:"Gender,omitempty"`
	RaceId         int32   `protobuf:"varint,8,opt,name=RaceId" json:"RaceId,omitempty"`
	BloodlineId    int32   `protobuf:"varint,9,opt,name=BloodlineId" json:"BloodlineId,omitempty"`
	AncestryId     int32   `protobuf:"varint,10,opt,name=AncestryId" json:"AncestryId,omitempty"`
	SecurityStatus float32 `protobuf:"fixed32,11,opt,name=SecurityStatus" json:"SecurityStatus,omitempty"`
}

func (m *Character) Reset()                    { *m = Character{} }
func (m *Character) String() string            { return proto.CompactTextString(m) }
func (*Character) ProtoMessage()               {}
func (*Character) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Character) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Character) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Character) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Character) GetCorporationId() int32 {
	if m != nil {
		return m.CorporationId
	}
	return 0
}

func (m *Character) GetAllianceId() int32 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func (m *Character) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *Character) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Character) GetRaceId() int32 {
	if m != nil {
		return m.RaceId
	}
	return 0
}

func (m *Character) GetBloodlineId() int32 {
	if m != nil {
		return m.BloodlineId
	}
	return 0
}

func (m *Character) GetAncestryId() int32 {
	if m != nil {
		return m.AncestryId
	}
	return 0
}

func (m *Character) GetSecurityStatus() float32 {
	if m != nil {
		return m.SecurityStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*EntityQueryRequest)(nil), "chremoas.esi.EntityQueryRequest")
	proto.RegisterType((*CharacterResponse)(nil), "chremoas.esi.CharacterResponse")
	proto.RegisterType((*Character)(nil), "chremoas.esi.Character")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CharacterQuery service

type CharacterQueryClient interface {
	GetCharacter(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*CharacterResponse, error)
}

type characterQueryClient struct {
	c           client.Client
	serviceName string
}

func NewCharacterQueryClient(serviceName string, c client.Client) CharacterQueryClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "chremoas.esi"
	}
	return &characterQueryClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *characterQueryClient) GetCharacter(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*CharacterResponse, error) {
	req := c.c.NewRequest(c.serviceName, "CharacterQuery.GetCharacter", in)
	out := new(CharacterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CharacterQuery service

type CharacterQueryHandler interface {
	GetCharacter(context.Context, *EntityQueryRequest, *CharacterResponse) error
}

func RegisterCharacterQueryHandler(s server.Server, hdlr CharacterQueryHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&CharacterQuery{hdlr}, opts...))
}

type CharacterQuery struct {
	CharacterQueryHandler
}

func (h *CharacterQuery) GetCharacter(ctx context.Context, in *EntityQueryRequest, out *CharacterResponse) error {
	return h.CharacterQueryHandler.GetCharacter(ctx, in, out)
}

func init() { proto.RegisterFile("character.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4e, 0xbb, 0x40,
	0x10, 0xc6, 0xff, 0xd0, 0x96, 0x7f, 0x3b, 0xad, 0x35, 0xee, 0x41, 0x37, 0x3d, 0x28, 0x21, 0xc6,
	0x70, 0x42, 0x53, 0x9f, 0xc0, 0xb6, 0xa6, 0xe1, 0x62, 0xe2, 0xf6, 0x09, 0x56, 0x98, 0xa4, 0x9b,
	0xd0, 0x5d, 0xdc, 0x5d, 0x0e, 0x3c, 0xa4, 0xef, 0x64, 0x58, 0x91, 0x52, 0x8d, 0x37, 0xbe, 0xdf,
	0x0c, 0xdf, 0x0c, 0xf3, 0x01, 0xe7, 0xd9, 0x9e, 0x6b, 0x9e, 0x59, 0xd4, 0x49, 0xa9, 0x95, 0x55,
	0x64, 0x96, 0xed, 0x35, 0x1e, 0x14, 0x37, 0x09, 0x1a, 0x11, 0x3d, 0x00, 0x79, 0x96, 0x56, 0xd8,
	0xfa, 0xb5, 0x42, 0x5d, 0x33, 0x7c, 0xaf, 0xd0, 0x58, 0xb2, 0x80, 0xf1, 0x17, 0x4d, 0x73, 0xea,
	0x85, 0x5e, 0x3c, 0x62, 0x9d, 0x8e, 0x36, 0x70, 0xb1, 0xfe, 0xb6, 0x64, 0x68, 0x4a, 0x25, 0x0d,
	0x92, 0x7b, 0x08, 0x18, 0x9a, 0xaa, 0xb0, 0xae, 0x7d, 0xba, 0xbc, 0x4a, 0xfa, 0x53, 0x92, 0xe3,
	0x0b, 0x6d, 0x5b, 0xf4, 0xe1, 0xc3, 0xa4, 0xa3, 0x64, 0x0e, 0x7e, 0x37, 0xc9, 0x4f, 0x73, 0x42,
	0x60, 0xf8, 0xc2, 0x0f, 0x48, 0xfd, 0xd0, 0x8b, 0x27, 0xcc, 0x3d, 0x93, 0x10, 0xa6, 0x1b, 0x34,
	0x99, 0x16, 0xa5, 0x15, 0x4a, 0xd2, 0x81, 0x2b, 0xf5, 0x11, 0xb9, 0x85, 0xb3, 0xb5, 0xd2, 0xa5,
	0xd2, 0xbc, 0x91, 0x69, 0x4e, 0x87, 0xce, 0xf0, 0x14, 0x92, 0x6b, 0x80, 0xa7, 0xa2, 0x10, 0x5c,
	0x66, 0x98, 0xe6, 0x74, 0xe4, 0x5a, 0x7a, 0xa4, 0xf9, 0xf6, 0x95, 0xd0, 0x76, 0x9f, 0xf3, 0x9a,
	0x06, 0xa1, 0x17, 0x0f, 0x58, 0xa7, 0xc9, 0x25, 0x04, 0x5b, 0x94, 0x39, 0x6a, 0xfa, 0xdf, 0x8d,
	0x6f, 0x55, 0xc3, 0x19, 0x77, 0x7e, 0x63, 0xe7, 0xd7, 0xaa, 0x66, 0xe7, 0x55, 0xa1, 0x54, 0x5e,
	0x08, 0xd9, 0x14, 0x27, 0xae, 0xd8, 0x47, 0x6e, 0x1b, 0x99, 0xa1, 0xb1, 0xba, 0xb9, 0x35, 0xb4,
	0xdb, 0x74, 0x84, 0xdc, 0xc1, 0x7c, 0x87, 0x59, 0xa5, 0x85, 0xad, 0x77, 0x96, 0xdb, 0xca, 0xd0,
	0x69, 0xe8, 0xc5, 0x3e, 0xfb, 0x41, 0x97, 0x08, 0xf3, 0xee, 0x9c, 0x2e, 0x4a, 0xb2, 0x83, 0xd9,
	0x16, 0xed, 0xf1, 0xc6, 0xe1, 0x69, 0x24, 0xbf, 0x53, 0x5f, 0xdc, 0xfc, 0x15, 0x5a, 0x9b, 0x72,
	0xf4, 0xef, 0x2d, 0x70, 0xff, 0xd0, 0xe3, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0xf4, 0x3f,
	0x7d, 0x56, 0x02, 0x00, 0x00,
}
