// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: character.proto

package chremoas_esi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CharacterService service

type CharacterService interface {
	GetCharacterById(ctx context.Context, in *GetCharacterByIdRequest, opts ...client.CallOption) (*GetCharacterByIdResponse, error)
}

type characterService struct {
	c    client.Client
	name string
}

func NewCharacterService(name string, c client.Client) CharacterService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "chremoas.esi"
	}
	return &characterService{
		c:    c,
		name: name,
	}
}

func (c *characterService) GetCharacterById(ctx context.Context, in *GetCharacterByIdRequest, opts ...client.CallOption) (*GetCharacterByIdResponse, error) {
	req := c.c.NewRequest(c.name, "CharacterService.GetCharacterById", in)
	out := new(GetCharacterByIdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CharacterService service

type CharacterServiceHandler interface {
	GetCharacterById(context.Context, *GetCharacterByIdRequest, *GetCharacterByIdResponse) error
}

func RegisterCharacterServiceHandler(s server.Server, hdlr CharacterServiceHandler, opts ...server.HandlerOption) {
	type characterService interface {
		GetCharacterById(ctx context.Context, in *GetCharacterByIdRequest, out *GetCharacterByIdResponse) error
	}
	type CharacterService struct {
		characterService
	}
	h := &characterServiceHandler{hdlr}
	s.Handle(s.NewHandler(&CharacterService{h}, opts...))
}

type characterServiceHandler struct {
	CharacterServiceHandler
}

func (h *characterServiceHandler) GetCharacterById(ctx context.Context, in *GetCharacterByIdRequest, out *GetCharacterByIdResponse) error {
	return h.CharacterServiceHandler.GetCharacterById(ctx, in, out)
}
