// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package chremoas_esi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EntityType int32

const (
	EntityType_ALLIANCE    EntityType = 0
	EntityType_CORPORATION EntityType = 1
	EntityType_CHARACTER   EntityType = 2
)

var EntityType_name = map[int32]string{
	0: "ALLIANCE",
	1: "CORPORATION",
	2: "CHARACTER",
}
var EntityType_value = map[string]int32{
	"ALLIANCE":    0,
	"CORPORATION": 1,
	"CHARACTER":   2,
}

func (x EntityType) String() string {
	return proto.EnumName(EntityType_name, int32(x))
}
func (EntityType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type Alliance struct {
	Name         string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Ticker       string `protobuf:"bytes,2,opt,name=Ticker" json:"Ticker,omitempty"`
	ExecutorCorp int32  `protobuf:"varint,3,opt,name=ExecutorCorp" json:"ExecutorCorp,omitempty"`
	DateFounded  int64  `protobuf:"varint,4,opt,name=DateFounded" json:"DateFounded,omitempty"`
}

func (m *Alliance) Reset()                    { *m = Alliance{} }
func (m *Alliance) String() string            { return proto.CompactTextString(m) }
func (*Alliance) ProtoMessage()               {}
func (*Alliance) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Alliance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Alliance) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *Alliance) GetExecutorCorp() int32 {
	if m != nil {
		return m.ExecutorCorp
	}
	return 0
}

func (m *Alliance) GetDateFounded() int64 {
	if m != nil {
		return m.DateFounded
	}
	return 0
}

type Icons struct {
	PSixtyFour      string `protobuf:"bytes,1,opt,name=PSixtyFour" json:"PSixtyFour,omitempty"`
	POneTwentyEight string `protobuf:"bytes,2,opt,name=POneTwentyEight" json:"POneTwentyEight,omitempty"`
}

func (m *Icons) Reset()                    { *m = Icons{} }
func (m *Icons) String() string            { return proto.CompactTextString(m) }
func (*Icons) ProtoMessage()               {}
func (*Icons) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *Icons) GetPSixtyFour() string {
	if m != nil {
		return m.PSixtyFour
	}
	return ""
}

func (m *Icons) GetPOneTwentyEight() string {
	if m != nil {
		return m.POneTwentyEight
	}
	return ""
}

type AllianceNames struct {
	AllianceId   int32  `protobuf:"varint,1,opt,name=AllianceId" json:"AllianceId,omitempty"`
	AllianceName string `protobuf:"bytes,2,opt,name=AllianceName" json:"AllianceName,omitempty"`
}

func (m *AllianceNames) Reset()                    { *m = AllianceNames{} }
func (m *AllianceNames) String() string            { return proto.CompactTextString(m) }
func (*AllianceNames) ProtoMessage()               {}
func (*AllianceNames) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *AllianceNames) GetAllianceId() int32 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func (m *AllianceNames) GetAllianceName() string {
	if m != nil {
		return m.AllianceName
	}
	return ""
}

type Character struct {
	Name           string  `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Description    string  `protobuf:"bytes,2,opt,name=Description" json:"Description,omitempty"`
	CorporationId  int32   `protobuf:"varint,3,opt,name=CorporationId" json:"CorporationId,omitempty"`
	AllianceId     int32   `protobuf:"varint,4,opt,name=AllianceId" json:"AllianceId,omitempty"`
	Birthday       int64   `protobuf:"varint,5,opt,name=Birthday" json:"Birthday,omitempty"`
	Gender         string  `protobuf:"bytes,6,opt,name=Gender" json:"Gender,omitempty"`
	RaceId         int32   `protobuf:"varint,7,opt,name=RaceId" json:"RaceId,omitempty"`
	BloodlineId    int32   `protobuf:"varint,8,opt,name=BloodlineId" json:"BloodlineId,omitempty"`
	AncestryId     int32   `protobuf:"varint,9,opt,name=AncestryId" json:"AncestryId,omitempty"`
	SecurityStatus float32 `protobuf:"fixed32,10,opt,name=SecurityStatus" json:"SecurityStatus,omitempty"`
}

func (m *Character) Reset()                    { *m = Character{} }
func (m *Character) String() string            { return proto.CompactTextString(m) }
func (*Character) ProtoMessage()               {}
func (*Character) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *Character) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Character) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Character) GetCorporationId() int32 {
	if m != nil {
		return m.CorporationId
	}
	return 0
}

func (m *Character) GetAllianceId() int32 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func (m *Character) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *Character) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Character) GetRaceId() int32 {
	if m != nil {
		return m.RaceId
	}
	return 0
}

func (m *Character) GetBloodlineId() int32 {
	if m != nil {
		return m.BloodlineId
	}
	return 0
}

func (m *Character) GetAncestryId() int32 {
	if m != nil {
		return m.AncestryId
	}
	return 0
}

func (m *Character) GetSecurityStatus() float32 {
	if m != nil {
		return m.SecurityStatus
	}
	return 0
}

type Corporation struct {
	Name         string  `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Ticker       string  `protobuf:"bytes,2,opt,name=Ticker" json:"Ticker,omitempty"`
	MemberCount  int32   `protobuf:"varint,3,opt,name=MemberCount" json:"MemberCount,omitempty"`
	CeoId        int32   `protobuf:"varint,4,opt,name=CeoId" json:"CeoId,omitempty"`
	AllianceId   int32   `protobuf:"varint,5,opt,name=AllianceId" json:"AllianceId,omitempty"`
	Description  string  `protobuf:"bytes,6,opt,name=Description" json:"Description,omitempty"`
	TaxRate      float32 `protobuf:"fixed32,7,opt,name=TaxRate" json:"TaxRate,omitempty"`
	CreationDate int64   `protobuf:"varint,8,opt,name=CreationDate" json:"CreationDate,omitempty"`
	CreatorId    int32   `protobuf:"varint,9,opt,name=CreatorId" json:"CreatorId,omitempty"`
	Url          string  `protobuf:"bytes,10,opt,name=Url" json:"Url,omitempty"`
	Faction      string  `protobuf:"bytes,11,opt,name=Faction" json:"Faction,omitempty"`
}

func (m *Corporation) Reset()                    { *m = Corporation{} }
func (m *Corporation) String() string            { return proto.CompactTextString(m) }
func (*Corporation) ProtoMessage()               {}
func (*Corporation) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *Corporation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Corporation) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *Corporation) GetMemberCount() int32 {
	if m != nil {
		return m.MemberCount
	}
	return 0
}

func (m *Corporation) GetCeoId() int32 {
	if m != nil {
		return m.CeoId
	}
	return 0
}

func (m *Corporation) GetAllianceId() int32 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func (m *Corporation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Corporation) GetTaxRate() float32 {
	if m != nil {
		return m.TaxRate
	}
	return 0
}

func (m *Corporation) GetCreationDate() int64 {
	if m != nil {
		return m.CreationDate
	}
	return 0
}

func (m *Corporation) GetCreatorId() int32 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func (m *Corporation) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Corporation) GetFaction() string {
	if m != nil {
		return m.Faction
	}
	return ""
}

func init() {
	proto.RegisterType((*Alliance)(nil), "chremoas.esi.Alliance")
	proto.RegisterType((*Icons)(nil), "chremoas.esi.Icons")
	proto.RegisterType((*AllianceNames)(nil), "chremoas.esi.AllianceNames")
	proto.RegisterType((*Character)(nil), "chremoas.esi.Character")
	proto.RegisterType((*Corporation)(nil), "chremoas.esi.Corporation")
	proto.RegisterEnum("chremoas.esi.EntityType", EntityType_name, EntityType_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x41, 0xaf, 0xd2, 0x40,
	0x14, 0x85, 0x6d, 0xa1, 0x3c, 0x7a, 0x01, 0x1f, 0x99, 0x18, 0xd3, 0x18, 0x63, 0x9a, 0xc6, 0x18,
	0xe2, 0xe2, 0x6d, 0xdc, 0xb9, 0xeb, 0xab, 0xa0, 0x4d, 0x9e, 0x80, 0x43, 0xfd, 0x01, 0xf3, 0xda,
	0x1b, 0x99, 0x08, 0x33, 0x64, 0x3a, 0x8d, 0x34, 0xf1, 0x9f, 0x19, 0xff, 0x9b, 0x99, 0xa1, 0x60,
	0x01, 0x37, 0xee, 0xe6, 0x7c, 0x13, 0x2e, 0xe7, 0x9c, 0x3b, 0x85, 0x61, 0x2e, 0xb7, 0x5b, 0x29,
	0xee, 0x76, 0x4a, 0x6a, 0x49, 0x86, 0xf9, 0x5a, 0xe1, 0x56, 0xb2, 0xf2, 0x0e, 0x4b, 0x1e, 0xfd,
	0x84, 0x7e, 0xbc, 0xd9, 0x70, 0x26, 0x72, 0x24, 0x04, 0xba, 0x73, 0xb6, 0xc5, 0xc0, 0x09, 0x9d,
	0x89, 0x4f, 0xed, 0x99, 0x3c, 0x87, 0x5e, 0xc6, 0xf3, 0xef, 0xa8, 0x02, 0xd7, 0xd2, 0x46, 0x91,
	0x08, 0x86, 0xd3, 0x3d, 0xe6, 0x95, 0x96, 0x2a, 0x91, 0x6a, 0x17, 0x74, 0x42, 0x67, 0xe2, 0xd1,
	0x33, 0x46, 0x42, 0x18, 0x7c, 0x60, 0x1a, 0x67, 0xb2, 0x12, 0x05, 0x16, 0x41, 0x37, 0x74, 0x26,
	0x1d, 0xda, 0x46, 0xd1, 0x17, 0xf0, 0xd2, 0x5c, 0x8a, 0x92, 0xbc, 0x02, 0x58, 0xae, 0xf8, 0x5e,
	0xd7, 0x33, 0x59, 0xa9, 0xc6, 0x40, 0x8b, 0x90, 0x09, 0xdc, 0x2e, 0x17, 0x02, 0xb3, 0x1f, 0x28,
	0x74, 0x3d, 0xe5, 0xdf, 0xd6, 0xba, 0xf1, 0x73, 0x89, 0xa3, 0x15, 0x8c, 0x8e, 0x81, 0x4c, 0x00,
	0x3b, 0xfa, 0x08, 0xd2, 0xc2, 0x8e, 0xf6, 0x68, 0x8b, 0x98, 0x24, 0xed, 0x1f, 0x34, 0x73, 0xcf,
	0x58, 0xf4, 0xdb, 0x05, 0x3f, 0x59, 0x33, 0xc5, 0x72, 0x8d, 0xea, 0x9f, 0x3d, 0x99, 0xac, 0x58,
	0xe6, 0x8a, 0xef, 0x34, 0x97, 0xa2, 0x19, 0xd2, 0x46, 0xe4, 0x35, 0x8c, 0x4c, 0x2b, 0x52, 0x31,
	0x23, 0xd3, 0xa2, 0xa9, 0xec, 0x1c, 0x5e, 0xb8, 0xed, 0x5e, 0xb9, 0x7d, 0x01, 0xfd, 0x7b, 0xae,
	0xf4, 0xba, 0x60, 0x75, 0xe0, 0xd9, 0x42, 0x4f, 0xda, 0xec, 0xea, 0x23, 0x8a, 0x02, 0x55, 0xd0,
	0x3b, 0xec, 0xea, 0xa0, 0x0c, 0xa7, 0xcc, 0xce, 0xbb, 0xb1, 0xf3, 0x1a, 0x65, 0x3c, 0xdf, 0x6f,
	0xa4, 0x2c, 0x36, 0x5c, 0x98, 0xcb, 0xbe, 0xbd, 0x6c, 0x23, 0xeb, 0x46, 0xe4, 0x58, 0x6a, 0x55,
	0xa7, 0x45, 0xe0, 0x37, 0x6e, 0x4e, 0x84, 0xbc, 0x81, 0xa7, 0x2b, 0xcc, 0x2b, 0xc5, 0x75, 0xbd,
	0xd2, 0x4c, 0x57, 0x65, 0x00, 0xa1, 0x33, 0x71, 0xe9, 0x05, 0x8d, 0x7e, 0xb9, 0x30, 0x68, 0xe5,
	0xfc, 0xaf, 0x97, 0x16, 0xc2, 0xe0, 0x33, 0x6e, 0x1f, 0x51, 0x25, 0xb2, 0x12, 0xba, 0x69, 0xad,
	0x8d, 0xc8, 0x33, 0xf0, 0x12, 0x94, 0xa7, 0xba, 0x0e, 0xe2, 0xa2, 0x49, 0xef, 0xaa, 0xc9, 0x8b,
	0x8d, 0xf5, 0xae, 0x37, 0x16, 0xc0, 0x4d, 0xc6, 0xf6, 0x94, 0x69, 0xb4, 0xc5, 0xb9, 0xf4, 0x28,
	0xcd, 0x9b, 0x49, 0x14, 0xda, 0x2c, 0xe6, 0x39, 0xdb, 0xea, 0x3a, 0xf4, 0x8c, 0x91, 0x97, 0xe0,
	0x5b, 0x2d, 0xd5, 0xa9, 0xba, 0xbf, 0x80, 0x8c, 0xa1, 0xf3, 0x55, 0x6d, 0x6c, 0x5d, 0x3e, 0x35,
	0x47, 0xf3, 0x6f, 0x33, 0x96, 0x5b, 0x2f, 0x03, 0x4b, 0x8f, 0xf2, 0xed, 0x7b, 0x80, 0xa9, 0xd0,
	0x5c, 0xd7, 0x59, 0xbd, 0x43, 0x32, 0x84, 0x7e, 0xfc, 0xf0, 0x90, 0xc6, 0xf3, 0x64, 0x3a, 0x7e,
	0x42, 0x6e, 0x61, 0x90, 0x2c, 0xe8, 0x72, 0x41, 0xe3, 0x2c, 0x5d, 0xcc, 0xc7, 0x0e, 0x19, 0x81,
	0x9f, 0x7c, 0x8a, 0x69, 0x9c, 0x64, 0x53, 0x3a, 0x76, 0x1f, 0x7b, 0xf6, 0xa3, 0x7f, 0xf7, 0x27,
	0x00, 0x00, 0xff, 0xff, 0x14, 0xd5, 0xfd, 0x6c, 0x04, 0x04, 0x00, 0x00,
}
