// Code generated by protoc-gen-go. DO NOT EDIT.
// source: esi-srv.proto

/*
Package chremoas_esi is a generated protocol buffer package.

It is generated from these files:
	esi-srv.proto

It has these top-level messages:
	EntityQueryRequest
	EntitySearchRequest
	AllianceResponse
	CorporationResponse
	CharacterResponse
	Alliance
	Corporation
	Character
	SearchResponse
*/
package chremoas_esi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EntityType int32

const (
	EntityType_ALLIANCE    EntityType = 0
	EntityType_CORPORATION EntityType = 1
	EntityType_CHARACTER   EntityType = 2
)

var EntityType_name = map[int32]string{
	0: "ALLIANCE",
	1: "CORPORATION",
	2: "CHARACTER",
}
var EntityType_value = map[string]int32{
	"ALLIANCE":    0,
	"CORPORATION": 1,
	"CHARACTER":   2,
}

func (x EntityType) String() string {
	return proto.EnumName(EntityType_name, int32(x))
}
func (EntityType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EntityQueryRequest struct {
	EntityId int32 `protobuf:"varint,1,opt,name=EntityId" json:"EntityId,omitempty"`
}

func (m *EntityQueryRequest) Reset()                    { *m = EntityQueryRequest{} }
func (m *EntityQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*EntityQueryRequest) ProtoMessage()               {}
func (*EntityQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EntityQueryRequest) GetEntityId() int32 {
	if m != nil {
		return m.EntityId
	}
	return 0
}

type EntitySearchRequest struct {
	SearchString string `protobuf:"bytes,1,opt,name=SearchString" json:"SearchString,omitempty"`
}

func (m *EntitySearchRequest) Reset()                    { *m = EntitySearchRequest{} }
func (m *EntitySearchRequest) String() string            { return proto.CompactTextString(m) }
func (*EntitySearchRequest) ProtoMessage()               {}
func (*EntitySearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EntitySearchRequest) GetSearchString() string {
	if m != nil {
		return m.SearchString
	}
	return ""
}

type AllianceResponse struct {
	Result *Alliance `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
}

func (m *AllianceResponse) Reset()                    { *m = AllianceResponse{} }
func (m *AllianceResponse) String() string            { return proto.CompactTextString(m) }
func (*AllianceResponse) ProtoMessage()               {}
func (*AllianceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AllianceResponse) GetResult() *Alliance {
	if m != nil {
		return m.Result
	}
	return nil
}

type CorporationResponse struct {
	Result *Corporation `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
}

func (m *CorporationResponse) Reset()                    { *m = CorporationResponse{} }
func (m *CorporationResponse) String() string            { return proto.CompactTextString(m) }
func (*CorporationResponse) ProtoMessage()               {}
func (*CorporationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CorporationResponse) GetResult() *Corporation {
	if m != nil {
		return m.Result
	}
	return nil
}

type CharacterResponse struct {
	Result *Character `protobuf:"bytes,1,opt,name=Result" json:"Result,omitempty"`
}

func (m *CharacterResponse) Reset()                    { *m = CharacterResponse{} }
func (m *CharacterResponse) String() string            { return proto.CompactTextString(m) }
func (*CharacterResponse) ProtoMessage()               {}
func (*CharacterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CharacterResponse) GetResult() *Character {
	if m != nil {
		return m.Result
	}
	return nil
}

type Alliance struct {
	Id           int32  `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Ticker       string `protobuf:"bytes,3,opt,name=Ticker" json:"Ticker,omitempty"`
	ExecutorCorp int32  `protobuf:"varint,4,opt,name=ExecutorCorp" json:"ExecutorCorp,omitempty"`
	DateFounded  int64  `protobuf:"varint,5,opt,name=DateFounded" json:"DateFounded,omitempty"`
}

func (m *Alliance) Reset()                    { *m = Alliance{} }
func (m *Alliance) String() string            { return proto.CompactTextString(m) }
func (*Alliance) ProtoMessage()               {}
func (*Alliance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Alliance) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Alliance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Alliance) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *Alliance) GetExecutorCorp() int32 {
	if m != nil {
		return m.ExecutorCorp
	}
	return 0
}

func (m *Alliance) GetDateFounded() int64 {
	if m != nil {
		return m.DateFounded
	}
	return 0
}

type Corporation struct {
	Id           int32   `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name         string  `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Ticker       string  `protobuf:"bytes,3,opt,name=Ticker" json:"Ticker,omitempty"`
	MemberCount  int32   `protobuf:"varint,4,opt,name=MemberCount" json:"MemberCount,omitempty"`
	CeoId        int32   `protobuf:"varint,5,opt,name=CeoId" json:"CeoId,omitempty"`
	AllianceId   int32   `protobuf:"varint,6,opt,name=AllianceId" json:"AllianceId,omitempty"`
	Description  string  `protobuf:"bytes,7,opt,name=Description" json:"Description,omitempty"`
	TaxRate      float32 `protobuf:"fixed32,8,opt,name=TaxRate" json:"TaxRate,omitempty"`
	CreationDate int64   `protobuf:"varint,9,opt,name=CreationDate" json:"CreationDate,omitempty"`
	CreatorId    int32   `protobuf:"varint,10,opt,name=CreatorId" json:"CreatorId,omitempty"`
	Url          string  `protobuf:"bytes,11,opt,name=Url" json:"Url,omitempty"`
	Faction      string  `protobuf:"bytes,12,opt,name=Faction" json:"Faction,omitempty"`
}

func (m *Corporation) Reset()                    { *m = Corporation{} }
func (m *Corporation) String() string            { return proto.CompactTextString(m) }
func (*Corporation) ProtoMessage()               {}
func (*Corporation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Corporation) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Corporation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Corporation) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *Corporation) GetMemberCount() int32 {
	if m != nil {
		return m.MemberCount
	}
	return 0
}

func (m *Corporation) GetCeoId() int32 {
	if m != nil {
		return m.CeoId
	}
	return 0
}

func (m *Corporation) GetAllianceId() int32 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func (m *Corporation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Corporation) GetTaxRate() float32 {
	if m != nil {
		return m.TaxRate
	}
	return 0
}

func (m *Corporation) GetCreationDate() int64 {
	if m != nil {
		return m.CreationDate
	}
	return 0
}

func (m *Corporation) GetCreatorId() int32 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func (m *Corporation) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Corporation) GetFaction() string {
	if m != nil {
		return m.Faction
	}
	return ""
}

type Character struct {
	Id             int32   `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	Name           string  `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Description    string  `protobuf:"bytes,3,opt,name=Description" json:"Description,omitempty"`
	CorporationId  int32   `protobuf:"varint,4,opt,name=CorporationId" json:"CorporationId,omitempty"`
	AllianceId     int32   `protobuf:"varint,5,opt,name=AllianceId" json:"AllianceId,omitempty"`
	Birthday       int64   `protobuf:"varint,6,opt,name=Birthday" json:"Birthday,omitempty"`
	Gender         string  `protobuf:"bytes,7,opt,name=Gender" json:"Gender,omitempty"`
	RaceId         int32   `protobuf:"varint,8,opt,name=RaceId" json:"RaceId,omitempty"`
	BloodlineId    int32   `protobuf:"varint,9,opt,name=BloodlineId" json:"BloodlineId,omitempty"`
	AncestryId     int32   `protobuf:"varint,10,opt,name=AncestryId" json:"AncestryId,omitempty"`
	SecurityStatus float32 `protobuf:"fixed32,11,opt,name=SecurityStatus" json:"SecurityStatus,omitempty"`
}

func (m *Character) Reset()                    { *m = Character{} }
func (m *Character) String() string            { return proto.CompactTextString(m) }
func (*Character) ProtoMessage()               {}
func (*Character) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Character) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Character) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Character) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Character) GetCorporationId() int32 {
	if m != nil {
		return m.CorporationId
	}
	return 0
}

func (m *Character) GetAllianceId() int32 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func (m *Character) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *Character) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Character) GetRaceId() int32 {
	if m != nil {
		return m.RaceId
	}
	return 0
}

func (m *Character) GetBloodlineId() int32 {
	if m != nil {
		return m.BloodlineId
	}
	return 0
}

func (m *Character) GetAncestryId() int32 {
	if m != nil {
		return m.AncestryId
	}
	return 0
}

func (m *Character) GetSecurityStatus() float32 {
	if m != nil {
		return m.SecurityStatus
	}
	return 0
}

type SearchResponse struct {
	Agent         []int32 `protobuf:"varint,1,rep,packed,name=Agent" json:"Agent,omitempty"`
	Alliance      []int32 `protobuf:"varint,2,rep,packed,name=Alliance" json:"Alliance,omitempty"`
	Character     []int32 `protobuf:"varint,3,rep,packed,name=Character" json:"Character,omitempty"`
	Constellation []int32 `protobuf:"varint,4,rep,packed,name=Constellation" json:"Constellation,omitempty"`
	Corporation   []int32 `protobuf:"varint,5,rep,packed,name=Corporation" json:"Corporation,omitempty"`
	Faction       []int32 `protobuf:"varint,6,rep,packed,name=Faction" json:"Faction,omitempty"`
	Inventorytype []int32 `protobuf:"varint,7,rep,packed,name=Inventorytype" json:"Inventorytype,omitempty"`
	Region        []int32 `protobuf:"varint,8,rep,packed,name=Region" json:"Region,omitempty"`
	Solarsystem   []int32 `protobuf:"varint,9,rep,packed,name=Solarsystem" json:"Solarsystem,omitempty"`
	Station       []int32 `protobuf:"varint,10,rep,packed,name=Station" json:"Station,omitempty"`
	Wormhole      []int32 `protobuf:"varint,11,rep,packed,name=Wormhole" json:"Wormhole,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *SearchResponse) GetAgent() []int32 {
	if m != nil {
		return m.Agent
	}
	return nil
}

func (m *SearchResponse) GetAlliance() []int32 {
	if m != nil {
		return m.Alliance
	}
	return nil
}

func (m *SearchResponse) GetCharacter() []int32 {
	if m != nil {
		return m.Character
	}
	return nil
}

func (m *SearchResponse) GetConstellation() []int32 {
	if m != nil {
		return m.Constellation
	}
	return nil
}

func (m *SearchResponse) GetCorporation() []int32 {
	if m != nil {
		return m.Corporation
	}
	return nil
}

func (m *SearchResponse) GetFaction() []int32 {
	if m != nil {
		return m.Faction
	}
	return nil
}

func (m *SearchResponse) GetInventorytype() []int32 {
	if m != nil {
		return m.Inventorytype
	}
	return nil
}

func (m *SearchResponse) GetRegion() []int32 {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *SearchResponse) GetSolarsystem() []int32 {
	if m != nil {
		return m.Solarsystem
	}
	return nil
}

func (m *SearchResponse) GetStation() []int32 {
	if m != nil {
		return m.Station
	}
	return nil
}

func (m *SearchResponse) GetWormhole() []int32 {
	if m != nil {
		return m.Wormhole
	}
	return nil
}

func init() {
	proto.RegisterType((*EntityQueryRequest)(nil), "chremoas.esi.EntityQueryRequest")
	proto.RegisterType((*EntitySearchRequest)(nil), "chremoas.esi.EntitySearchRequest")
	proto.RegisterType((*AllianceResponse)(nil), "chremoas.esi.AllianceResponse")
	proto.RegisterType((*CorporationResponse)(nil), "chremoas.esi.CorporationResponse")
	proto.RegisterType((*CharacterResponse)(nil), "chremoas.esi.CharacterResponse")
	proto.RegisterType((*Alliance)(nil), "chremoas.esi.Alliance")
	proto.RegisterType((*Corporation)(nil), "chremoas.esi.Corporation")
	proto.RegisterType((*Character)(nil), "chremoas.esi.Character")
	proto.RegisterType((*SearchResponse)(nil), "chremoas.esi.SearchResponse")
	proto.RegisterEnum("chremoas.esi.EntityType", EntityType_name, EntityType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for EntityQuery service

type EntityQueryClient interface {
	GetAlliance(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*AllianceResponse, error)
	GetCorporation(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*CorporationResponse, error)
	GetCharacter(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*CharacterResponse, error)
	GetSearch(ctx context.Context, in *EntitySearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type entityQueryClient struct {
	c           client.Client
	serviceName string
}

func NewEntityQueryClient(serviceName string, c client.Client) EntityQueryClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "chremoas.esi"
	}
	return &entityQueryClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *entityQueryClient) GetAlliance(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*AllianceResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EntityQuery.GetAlliance", in)
	out := new(AllianceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityQueryClient) GetCorporation(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*CorporationResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EntityQuery.GetCorporation", in)
	out := new(CorporationResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityQueryClient) GetCharacter(ctx context.Context, in *EntityQueryRequest, opts ...client.CallOption) (*CharacterResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EntityQuery.GetCharacter", in)
	out := new(CharacterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityQueryClient) GetSearch(ctx context.Context, in *EntitySearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "EntityQuery.GetSearch", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EntityQuery service

type EntityQueryHandler interface {
	GetAlliance(context.Context, *EntityQueryRequest, *AllianceResponse) error
	GetCorporation(context.Context, *EntityQueryRequest, *CorporationResponse) error
	GetCharacter(context.Context, *EntityQueryRequest, *CharacterResponse) error
	GetSearch(context.Context, *EntitySearchRequest, *SearchResponse) error
}

func RegisterEntityQueryHandler(s server.Server, hdlr EntityQueryHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&EntityQuery{hdlr}, opts...))
}

type EntityQuery struct {
	EntityQueryHandler
}

func (h *EntityQuery) GetAlliance(ctx context.Context, in *EntityQueryRequest, out *AllianceResponse) error {
	return h.EntityQueryHandler.GetAlliance(ctx, in, out)
}

func (h *EntityQuery) GetCorporation(ctx context.Context, in *EntityQueryRequest, out *CorporationResponse) error {
	return h.EntityQueryHandler.GetCorporation(ctx, in, out)
}

func (h *EntityQuery) GetCharacter(ctx context.Context, in *EntityQueryRequest, out *CharacterResponse) error {
	return h.EntityQueryHandler.GetCharacter(ctx, in, out)
}

func (h *EntityQuery) GetSearch(ctx context.Context, in *EntitySearchRequest, out *SearchResponse) error {
	return h.EntityQueryHandler.GetSearch(ctx, in, out)
}

func init() { proto.RegisterFile("esi-srv.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 799 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xdb, 0x46,
	0x10, 0xb5, 0x28, 0x4b, 0x16, 0x87, 0xb2, 0xab, 0x6e, 0x82, 0x74, 0x6b, 0x18, 0xa9, 0x42, 0x14,
	0x85, 0x51, 0xa0, 0x6a, 0x9b, 0x9e, 0xda, 0x9b, 0xcc, 0x38, 0x0e, 0x81, 0xd4, 0x6e, 0x56, 0x2a,
	0x72, 0x66, 0xc8, 0x81, 0x45, 0x94, 0xe2, 0xaa, 0xcb, 0x65, 0x10, 0xfd, 0x87, 0xfe, 0xb3, 0xa2,
	0xf7, 0x9e, 0xfa, 0x5b, 0x8a, 0x1d, 0x7e, 0x68, 0x29, 0xd7, 0x70, 0x81, 0xdc, 0xf8, 0xde, 0xee,
	0xbe, 0x99, 0x79, 0xc3, 0x9d, 0x85, 0x63, 0x2c, 0xd2, 0x6f, 0x0a, 0xf5, 0x7e, 0xb6, 0x51, 0x52,
	0x4b, 0x36, 0x8e, 0x57, 0x0a, 0xd7, 0x32, 0x2a, 0x66, 0x58, 0xa4, 0xfe, 0x77, 0xc0, 0x2e, 0x73,
	0x9d, 0xea, 0xed, 0x9b, 0x12, 0xd5, 0x56, 0xe0, 0xef, 0x25, 0x16, 0x9a, 0x9d, 0xc2, 0xa8, 0x62,
	0xc3, 0x84, 0xf7, 0xa6, 0xbd, 0xf3, 0x81, 0x68, 0xb1, 0xff, 0x23, 0x3c, 0xaa, 0xbe, 0x17, 0x18,
	0xa9, 0x78, 0xd5, 0x1c, 0xf1, 0x61, 0x5c, 0x11, 0x0b, 0xad, 0xd2, 0xfc, 0x96, 0x8e, 0xb9, 0xa2,
	0xc3, 0xf9, 0x17, 0x30, 0x99, 0x67, 0x59, 0x1a, 0xe5, 0x31, 0x0a, 0x2c, 0x36, 0x32, 0x2f, 0x90,
	0xcd, 0x60, 0x28, 0xb0, 0x28, 0x33, 0x4d, 0x27, 0xbc, 0xe7, 0x4f, 0x66, 0x76, 0x7e, 0xb3, 0x76,
	0x7f, 0xbd, 0xcb, 0x7f, 0x05, 0x8f, 0x02, 0xa9, 0x36, 0x52, 0x45, 0x3a, 0x95, 0x79, 0x2b, 0xf3,
	0xfd, 0x9e, 0xcc, 0xe7, 0x5d, 0x19, 0xfb, 0x48, 0xa3, 0xf4, 0x02, 0x3e, 0x0d, 0x56, 0x91, 0x8a,
	0x62, 0x8d, 0xaa, 0xd5, 0xf9, 0x76, 0x4f, 0xe7, 0xb3, 0x3d, 0x9d, 0xf6, 0x40, 0xa3, 0xf2, 0x47,
	0x0f, 0x46, 0x4d, 0x92, 0xec, 0x04, 0x9c, 0xd6, 0x31, 0x27, 0x4c, 0x18, 0x83, 0xc3, 0xeb, 0x68,
	0x8d, 0xdc, 0x21, 0x33, 0xe8, 0x9b, 0x3d, 0x81, 0xe1, 0x32, 0x8d, 0x7f, 0x43, 0xc5, 0xfb, 0xc4,
	0xd6, 0xc8, 0x18, 0x78, 0xf9, 0x01, 0xe3, 0x52, 0x4b, 0x65, 0xb2, 0xe5, 0x87, 0xa4, 0xd2, 0xe1,
	0xd8, 0x14, 0xbc, 0x17, 0x91, 0xc6, 0x97, 0xb2, 0xcc, 0x13, 0x4c, 0xf8, 0x60, 0xda, 0x3b, 0xef,
	0x0b, 0x9b, 0xf2, 0xff, 0x74, 0xc0, 0xb3, 0x8a, 0xfd, 0xa8, 0x8c, 0xa6, 0xe0, 0xfd, 0x8c, 0xeb,
	0x77, 0xa8, 0x02, 0x59, 0xe6, 0xba, 0x4e, 0xc8, 0xa6, 0xd8, 0x63, 0x18, 0x04, 0x28, 0xc3, 0x2a,
	0x93, 0x81, 0xa8, 0x00, 0x7b, 0x0a, 0xd0, 0x38, 0x12, 0x26, 0x7c, 0x48, 0x4b, 0x16, 0x43, 0x55,
	0x60, 0x11, 0xab, 0x74, 0x63, 0x52, 0xe4, 0x47, 0x14, 0xd4, 0xa6, 0x18, 0x87, 0xa3, 0x65, 0xf4,
	0x41, 0x44, 0x1a, 0xf9, 0x68, 0xda, 0x3b, 0x77, 0x44, 0x03, 0x8d, 0x4b, 0x81, 0x42, 0xaa, 0xcd,
	0x94, 0xcd, 0x5d, 0xb2, 0xa0, 0xc3, 0xb1, 0x33, 0x70, 0x09, 0x4b, 0x15, 0x26, 0x1c, 0x28, 0xfc,
	0x8e, 0x60, 0x13, 0xe8, 0xff, 0xaa, 0x32, 0xee, 0x51, 0x54, 0xf3, 0x69, 0xa2, 0xbd, 0x8c, 0x62,
	0xca, 0x65, 0x4c, 0x6c, 0x03, 0xfd, 0xbf, 0x1c, 0x70, 0xdb, 0x96, 0xff, 0x2f, 0x2f, 0xf7, 0x6a,
	0xeb, 0xdf, 0xad, 0xed, 0x4b, 0x38, 0xb6, 0x1a, 0x14, 0x26, 0xb5, 0xaf, 0x5d, 0x72, 0xcf, 0xc3,
	0xc1, 0x1d, 0x0f, 0x4f, 0x61, 0x74, 0x91, 0x2a, 0xbd, 0x4a, 0xa2, 0x2d, 0x39, 0xdc, 0x17, 0x2d,
	0x36, 0xfd, 0xbc, 0xc2, 0x3c, 0x41, 0x55, 0x5b, 0x5b, 0x23, 0xc3, 0x8b, 0x88, 0xf4, 0x46, 0xa4,
	0x57, 0x23, 0x93, 0xf3, 0x45, 0x26, 0x65, 0x92, 0xa5, 0xb9, 0x59, 0x74, 0xab, 0x3e, 0x5b, 0x14,
	0x65, 0x93, 0xc7, 0x58, 0x68, 0xb5, 0x6d, 0x2d, 0xb5, 0x18, 0xf6, 0x15, 0x9c, 0x2c, 0x30, 0x2e,
	0x95, 0x99, 0x0a, 0x3a, 0xd2, 0x65, 0x41, 0xf6, 0x3a, 0x62, 0x8f, 0xf5, 0xff, 0x76, 0xcc, 0xc6,
	0x6a, 0x6c, 0xd4, 0x17, 0xee, 0x31, 0x0c, 0xe6, 0xb7, 0x98, 0x9b, 0xfb, 0xd6, 0x37, 0xbf, 0x10,
	0x01, 0x53, 0x5e, 0x53, 0x2c, 0x77, 0x68, 0x61, 0x77, 0xc9, 0xce, 0xac, 0x9e, 0xf0, 0x3e, 0x2d,
	0x5a, 0x4d, 0x22, 0x7b, 0xf3, 0x42, 0x63, 0x96, 0x91, 0x97, 0xfc, 0x90, 0x76, 0x74, 0x49, 0x53,
	0xb2, 0xe5, 0x37, 0x1f, 0xd0, 0x9e, 0xce, 0xc5, 0xb1, 0x7e, 0x8a, 0x21, 0xad, 0x36, 0xd0, 0x44,
	0x08, 0xf3, 0xf7, 0x98, 0x6b, 0xa9, 0xb6, 0x7a, 0xbb, 0x41, 0x7e, 0x54, 0x45, 0xe8, 0x90, 0x64,
	0x36, 0xde, 0x9a, 0xe3, 0x23, 0x5a, 0xae, 0x91, 0x89, 0xbc, 0x90, 0x59, 0xa4, 0x8a, 0x6d, 0xa1,
	0x71, 0xcd, 0xdd, 0x2a, 0xb2, 0x45, 0x99, 0xc8, 0xc6, 0x2e, 0x73, 0x14, 0xaa, 0xc8, 0x35, 0x34,
	0xae, 0xbc, 0x95, 0x6a, 0xbd, 0x92, 0x19, 0x72, 0xaf, 0x72, 0xa5, 0xc1, 0x5f, 0xff, 0x04, 0x50,
	0x8d, 0xe5, 0xa5, 0x89, 0x3e, 0x86, 0xd1, 0xfc, 0xf5, 0xeb, 0x70, 0x7e, 0x1d, 0x5c, 0x4e, 0x0e,
	0xd8, 0x27, 0xe0, 0x05, 0x37, 0xe2, 0x97, 0x1b, 0x31, 0x5f, 0x86, 0x37, 0xd7, 0x93, 0x1e, 0x3b,
	0x06, 0x37, 0x78, 0x35, 0x17, 0xf3, 0x60, 0x79, 0x29, 0x26, 0xce, 0xf3, 0x7f, 0x1c, 0xf0, 0xac,
	0x57, 0x80, 0xbd, 0x01, 0xef, 0x0a, 0x75, 0x6b, 0xf8, 0xb4, 0x3b, 0x03, 0xef, 0xbe, 0x17, 0xa7,
	0x4f, 0xef, 0x19, 0xda, 0x75, 0x93, 0xfd, 0x03, 0xf6, 0x16, 0x4e, 0xae, 0x50, 0xdb, 0x06, 0x3f,
	0xac, 0xfa, 0xec, 0xfe, 0x19, 0xbe, 0x13, 0x5e, 0xc0, 0xd8, 0x08, 0xb7, 0xfd, 0x7f, 0x58, 0xf6,
	0x8b, 0xfb, 0x46, 0xfa, 0x4e, 0xf4, 0x1a, 0xdc, 0x2b, 0xd4, 0xd5, 0x9f, 0xca, 0x9e, 0xfd, 0x97,
	0x62, 0xe7, 0xf1, 0x3b, 0x3d, 0xeb, 0x6e, 0xe9, 0xfe, 0xe2, 0xfe, 0xc1, 0xbb, 0x21, 0x3d, 0xbd,
	0x3f, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x4f, 0xed, 0x62, 0x8b, 0x07, 0x00, 0x00,
}
