//// Automatically generated by pegomock. DO NOT EDIT!
//// Source: github.com/chremoas/esi-srv/proto (interfaces: AllianceServiceClient)
//
package esi_mocks
//
//import (
//	context "golang.org/x/net/context"
//	proto "github.com/chremoas/esi-srv/proto"
//	client "github.com/micro/go-micro/client"
//	pegomock "github.com/petergtz/pegomock"
//	"reflect"
//)
//
//type MockAllianceServiceClient struct {
//	fail func(message string, callerSkip ...int)
//}
//
//func NewMockAllianceServiceClient() *MockAllianceServiceClient {
//	return &MockAllianceServiceClient{fail: pegomock.GlobalFailHandler}
//}
//
//func (mock *MockAllianceServiceClient) GetAllianceById(_param0 context.Context, _param1 *proto.GetAllianceByIdRequest, _param2 ...client.CallOption) (*proto.GetAllianceByIdResponse, error) {
//	params := []pegomock.Param{_param0, _param1}
//	for _, param := range _param2 {
//		params = append(params, param)
//	}
//	result := pegomock.GetGenericMockFrom(mock).Invoke("GetAllianceById", params, []reflect.Type{reflect.TypeOf((**proto.GetAllianceByIdResponse)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
//	var ret0 *proto.GetAllianceByIdResponse
//	var ret1 error
//	if len(result) != 0 {
//		if result[0] != nil {
//			ret0 = result[0].(*proto.GetAllianceByIdResponse)
//		}
//		if result[1] != nil {
//			ret1 = result[1].(error)
//		}
//	}
//	return ret0, ret1
//}
//
//func (mock *MockAllianceServiceClient) GetAllianceCorporationsById(_param0 context.Context, _param1 *proto.GetAllianceCorporationsByIdRequest, _param2 ...client.CallOption) (*proto.GetAllianceCorporationsByIdResponse, error) {
//	params := []pegomock.Param{_param0, _param1}
//	for _, param := range _param2 {
//		params = append(params, param)
//	}
//	result := pegomock.GetGenericMockFrom(mock).Invoke("GetAllianceCorporationsById", params, []reflect.Type{reflect.TypeOf((**proto.GetAllianceCorporationsByIdResponse)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
//	var ret0 *proto.GetAllianceCorporationsByIdResponse
//	var ret1 error
//	if len(result) != 0 {
//		if result[0] != nil {
//			ret0 = result[0].(*proto.GetAllianceCorporationsByIdResponse)
//		}
//		if result[1] != nil {
//			ret1 = result[1].(error)
//		}
//	}
//	return ret0, ret1
//}
//
//func (mock *MockAllianceServiceClient) GetAllianceIconsById(_param0 context.Context, _param1 *proto.GetAllianceIconsByIdRequest, _param2 ...client.CallOption) (*proto.GetAllianceIconsByIdResponse, error) {
//	params := []pegomock.Param{_param0, _param1}
//	for _, param := range _param2 {
//		params = append(params, param)
//	}
//	result := pegomock.GetGenericMockFrom(mock).Invoke("GetAllianceIconsById", params, []reflect.Type{reflect.TypeOf((**proto.GetAllianceIconsByIdResponse)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
//	var ret0 *proto.GetAllianceIconsByIdResponse
//	var ret1 error
//	if len(result) != 0 {
//		if result[0] != nil {
//			ret0 = result[0].(*proto.GetAllianceIconsByIdResponse)
//		}
//		if result[1] != nil {
//			ret1 = result[1].(error)
//		}
//	}
//	return ret0, ret1
//}
//
//func (mock *MockAllianceServiceClient) GetAllianceNamesByIds(_param0 context.Context, _param1 *proto.GetAllianceNamesByIdsRequest, _param2 ...client.CallOption) (*proto.GetAllianceNamesByIdsResponse, error) {
//	params := []pegomock.Param{_param0, _param1}
//	for _, param := range _param2 {
//		params = append(params, param)
//	}
//	result := pegomock.GetGenericMockFrom(mock).Invoke("GetAllianceNamesByIds", params, []reflect.Type{reflect.TypeOf((**proto.GetAllianceNamesByIdsResponse)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
//	var ret0 *proto.GetAllianceNamesByIdsResponse
//	var ret1 error
//	if len(result) != 0 {
//		if result[0] != nil {
//			ret0 = result[0].(*proto.GetAllianceNamesByIdsResponse)
//		}
//		if result[1] != nil {
//			ret1 = result[1].(error)
//		}
//	}
//	return ret0, ret1
//}
//
//func (mock *MockAllianceServiceClient) GetAlliances(_param0 context.Context, _param1 *proto.GetAlliancesRequest, _param2 ...client.CallOption) (*proto.GetAlliancesResponse, error) {
//	params := []pegomock.Param{_param0, _param1}
//	for _, param := range _param2 {
//		params = append(params, param)
//	}
//	result := pegomock.GetGenericMockFrom(mock).Invoke("GetAlliances", params, []reflect.Type{reflect.TypeOf((**proto.GetAlliancesResponse)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
//	var ret0 *proto.GetAlliancesResponse
//	var ret1 error
//	if len(result) != 0 {
//		if result[0] != nil {
//			ret0 = result[0].(*proto.GetAlliancesResponse)
//		}
//		if result[1] != nil {
//			ret1 = result[1].(error)
//		}
//	}
//	return ret0, ret1
//}
//
//func (mock *MockAllianceServiceClient) VerifyWasCalledOnce() *VerifierAllianceServiceClient {
//	return &VerifierAllianceServiceClient{mock, pegomock.Times(1), nil}
//}
//
//func (mock *MockAllianceServiceClient) VerifyWasCalled(invocationCountMatcher pegomock.Matcher) *VerifierAllianceServiceClient {
//	return &VerifierAllianceServiceClient{mock, invocationCountMatcher, nil}
//}
//
//func (mock *MockAllianceServiceClient) VerifyWasCalledInOrder(invocationCountMatcher pegomock.Matcher, inOrderContext *pegomock.InOrderContext) *VerifierAllianceServiceClient {
//	return &VerifierAllianceServiceClient{mock, invocationCountMatcher, inOrderContext}
//}
//
//type VerifierAllianceServiceClient struct {
//	mock                   *MockAllianceServiceClient
//	invocationCountMatcher pegomock.Matcher
//	inOrderContext         *pegomock.InOrderContext
//}
//
//func (verifier *VerifierAllianceServiceClient) GetAllianceById(_param0 context.Context, _param1 *proto.GetAllianceByIdRequest, _param2 ...client.CallOption) *AllianceServiceClient_GetAllianceById_OngoingVerification {
//	params := []pegomock.Param{_param0, _param1}
//	for _, param := range _param2 {
//		params = append(params, param)
//	}
//	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GetAllianceById", params)
//	return &AllianceServiceClient_GetAllianceById_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
//}
//
//type AllianceServiceClient_GetAllianceById_OngoingVerification struct {
//	mock              *MockAllianceServiceClient
//	methodInvocations []pegomock.MethodInvocation
//}
//
//func (c *AllianceServiceClient_GetAllianceById_OngoingVerification) GetCapturedArguments() (context.Context, *proto.GetAllianceByIdRequest, []client.CallOption) {
//	_param0, _param1, _param2 := c.GetAllCapturedArguments()
//	return _param0[len(_param0)-1], _param1[len(_param1)-1], _param2[len(_param2)-1]
//}
//
//func (c *AllianceServiceClient_GetAllianceById_OngoingVerification) GetAllCapturedArguments() (_param0 []context.Context, _param1 []*proto.GetAllianceByIdRequest, _param2 [][]client.CallOption) {
//	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
//	if len(params) > 0 {
//		_param0 = make([]context.Context, len(params[0]))
//		for u, param := range params[0] {
//			_param0[u] = param.(context.Context)
//		}
//		_param1 = make([]*proto.GetAllianceByIdRequest, len(params[1]))
//		for u, param := range params[1] {
//			_param1[u] = param.(*proto.GetAllianceByIdRequest)
//		}
//		_param2 = make([][]client.CallOption, len(params[2]))
//		for u := range params[0] {
//			_param2[u] = make([]client.CallOption, len(params)-2)
//			for x := 2; x < len(params); x++ {
//				if params[x][u] != nil {
//					_param2[u][x-2] = params[x][u].(client.CallOption)
//				}
//			}
//		}
//	}
//	return
//}
//
//func (verifier *VerifierAllianceServiceClient) GetAllianceCorporationsById(_param0 context.Context, _param1 *proto.GetAllianceCorporationsByIdRequest, _param2 ...client.CallOption) *AllianceServiceClient_GetAllianceCorporationsById_OngoingVerification {
//	params := []pegomock.Param{_param0, _param1}
//	for _, param := range _param2 {
//		params = append(params, param)
//	}
//	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GetAllianceCorporationsById", params)
//	return &AllianceServiceClient_GetAllianceCorporationsById_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
//}
//
//type AllianceServiceClient_GetAllianceCorporationsById_OngoingVerification struct {
//	mock              *MockAllianceServiceClient
//	methodInvocations []pegomock.MethodInvocation
//}
//
//func (c *AllianceServiceClient_GetAllianceCorporationsById_OngoingVerification) GetCapturedArguments() (context.Context, *proto.GetAllianceCorporationsByIdRequest, []client.CallOption) {
//	_param0, _param1, _param2 := c.GetAllCapturedArguments()
//	return _param0[len(_param0)-1], _param1[len(_param1)-1], _param2[len(_param2)-1]
//}
//
//func (c *AllianceServiceClient_GetAllianceCorporationsById_OngoingVerification) GetAllCapturedArguments() (_param0 []context.Context, _param1 []*proto.GetAllianceCorporationsByIdRequest, _param2 [][]client.CallOption) {
//	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
//	if len(params) > 0 {
//		_param0 = make([]context.Context, len(params[0]))
//		for u, param := range params[0] {
//			_param0[u] = param.(context.Context)
//		}
//		_param1 = make([]*proto.GetAllianceCorporationsByIdRequest, len(params[1]))
//		for u, param := range params[1] {
//			_param1[u] = param.(*proto.GetAllianceCorporationsByIdRequest)
//		}
//		_param2 = make([][]client.CallOption, len(params[2]))
//		for u := range params[0] {
//			_param2[u] = make([]client.CallOption, len(params)-2)
//			for x := 2; x < len(params); x++ {
//				if params[x][u] != nil {
//					_param2[u][x-2] = params[x][u].(client.CallOption)
//				}
//			}
//		}
//	}
//	return
//}
//
//func (verifier *VerifierAllianceServiceClient) GetAllianceIconsById(_param0 context.Context, _param1 *proto.GetAllianceIconsByIdRequest, _param2 ...client.CallOption) *AllianceServiceClient_GetAllianceIconsById_OngoingVerification {
//	params := []pegomock.Param{_param0, _param1}
//	for _, param := range _param2 {
//		params = append(params, param)
//	}
//	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GetAllianceIconsById", params)
//	return &AllianceServiceClient_GetAllianceIconsById_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
//}
//
//type AllianceServiceClient_GetAllianceIconsById_OngoingVerification struct {
//	mock              *MockAllianceServiceClient
//	methodInvocations []pegomock.MethodInvocation
//}
//
//func (c *AllianceServiceClient_GetAllianceIconsById_OngoingVerification) GetCapturedArguments() (context.Context, *proto.GetAllianceIconsByIdRequest, []client.CallOption) {
//	_param0, _param1, _param2 := c.GetAllCapturedArguments()
//	return _param0[len(_param0)-1], _param1[len(_param1)-1], _param2[len(_param2)-1]
//}
//
//func (c *AllianceServiceClient_GetAllianceIconsById_OngoingVerification) GetAllCapturedArguments() (_param0 []context.Context, _param1 []*proto.GetAllianceIconsByIdRequest, _param2 [][]client.CallOption) {
//	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
//	if len(params) > 0 {
//		_param0 = make([]context.Context, len(params[0]))
//		for u, param := range params[0] {
//			_param0[u] = param.(context.Context)
//		}
//		_param1 = make([]*proto.GetAllianceIconsByIdRequest, len(params[1]))
//		for u, param := range params[1] {
//			_param1[u] = param.(*proto.GetAllianceIconsByIdRequest)
//		}
//		_param2 = make([][]client.CallOption, len(params[2]))
//		for u := range params[0] {
//			_param2[u] = make([]client.CallOption, len(params)-2)
//			for x := 2; x < len(params); x++ {
//				if params[x][u] != nil {
//					_param2[u][x-2] = params[x][u].(client.CallOption)
//				}
//			}
//		}
//	}
//	return
//}
//
//func (verifier *VerifierAllianceServiceClient) GetAllianceNamesByIds(_param0 context.Context, _param1 *proto.GetAllianceNamesByIdsRequest, _param2 ...client.CallOption) *AllianceServiceClient_GetAllianceNamesByIds_OngoingVerification {
//	params := []pegomock.Param{_param0, _param1}
//	for _, param := range _param2 {
//		params = append(params, param)
//	}
//	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GetAllianceNamesByIds", params)
//	return &AllianceServiceClient_GetAllianceNamesByIds_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
//}
//
//type AllianceServiceClient_GetAllianceNamesByIds_OngoingVerification struct {
//	mock              *MockAllianceServiceClient
//	methodInvocations []pegomock.MethodInvocation
//}
//
//func (c *AllianceServiceClient_GetAllianceNamesByIds_OngoingVerification) GetCapturedArguments() (context.Context, *proto.GetAllianceNamesByIdsRequest, []client.CallOption) {
//	_param0, _param1, _param2 := c.GetAllCapturedArguments()
//	return _param0[len(_param0)-1], _param1[len(_param1)-1], _param2[len(_param2)-1]
//}
//
//func (c *AllianceServiceClient_GetAllianceNamesByIds_OngoingVerification) GetAllCapturedArguments() (_param0 []context.Context, _param1 []*proto.GetAllianceNamesByIdsRequest, _param2 [][]client.CallOption) {
//	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
//	if len(params) > 0 {
//		_param0 = make([]context.Context, len(params[0]))
//		for u, param := range params[0] {
//			_param0[u] = param.(context.Context)
//		}
//		_param1 = make([]*proto.GetAllianceNamesByIdsRequest, len(params[1]))
//		for u, param := range params[1] {
//			_param1[u] = param.(*proto.GetAllianceNamesByIdsRequest)
//		}
//		_param2 = make([][]client.CallOption, len(params[2]))
//		for u := range params[0] {
//			_param2[u] = make([]client.CallOption, len(params)-2)
//			for x := 2; x < len(params); x++ {
//				if params[x][u] != nil {
//					_param2[u][x-2] = params[x][u].(client.CallOption)
//				}
//			}
//		}
//	}
//	return
//}
//
//func (verifier *VerifierAllianceServiceClient) GetAlliances(_param0 context.Context, _param1 *proto.GetAlliancesRequest, _param2 ...client.CallOption) *AllianceServiceClient_GetAlliances_OngoingVerification {
//	params := []pegomock.Param{_param0, _param1}
//	for _, param := range _param2 {
//		params = append(params, param)
//	}
//	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GetAlliances", params)
//	return &AllianceServiceClient_GetAlliances_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
//}
//
//type AllianceServiceClient_GetAlliances_OngoingVerification struct {
//	mock              *MockAllianceServiceClient
//	methodInvocations []pegomock.MethodInvocation
//}
//
//func (c *AllianceServiceClient_GetAlliances_OngoingVerification) GetCapturedArguments() (context.Context, *proto.GetAlliancesRequest, []client.CallOption) {
//	_param0, _param1, _param2 := c.GetAllCapturedArguments()
//	return _param0[len(_param0)-1], _param1[len(_param1)-1], _param2[len(_param2)-1]
//}
//
//func (c *AllianceServiceClient_GetAlliances_OngoingVerification) GetAllCapturedArguments() (_param0 []context.Context, _param1 []*proto.GetAlliancesRequest, _param2 [][]client.CallOption) {
//	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
//	if len(params) > 0 {
//		_param0 = make([]context.Context, len(params[0]))
//		for u, param := range params[0] {
//			_param0[u] = param.(context.Context)
//		}
//		_param1 = make([]*proto.GetAlliancesRequest, len(params[1]))
//		for u, param := range params[1] {
//			_param1[u] = param.(*proto.GetAlliancesRequest)
//		}
//		_param2 = make([][]client.CallOption, len(params[2]))
//		for u := range params[0] {
//			_param2[u] = make([]client.CallOption, len(params)-2)
//			for x := 2; x < len(params); x++ {
//				if params[x][u] != nil {
//					_param2[u][x-2] = params[x][u].(client.CallOption)
//				}
//			}
//		}
//	}
//	return
//}
